config/routes.rb
Rails.application.routes.draw do
  resources :users
  # resources :users, only: [:new, :create etc] to leave out unwanted paths
  resources :posts
  
  # get '/destroy/post', to: 'posts#destroy'
  # delete '/destroy/post', to: 'posts#destroy'
  
  post '/show', to: 'posts#show'
  
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  # belongs_to :user
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  
  has_secure_password
  
  validates :username, presence: true, length: {maximum: 20}, uniqueness: { case_sensitive: true }
  validates :name, presence: true, length: {maximum: 20}
  validates :email, :email_format => { :message => 'That\'s not an email!' },
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 4, maximum: 254 }
    validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  validates :password, presence: true, length: { minimum: 7, message: 'Password cannot be fewer than 7 characters!' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  private

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = Post.create!(post_params)

    respond_to do |format|
      if @post.save
        flash[:success] = "Your post has been created!"
        format.html { redirect_to @post}
        format.json { render :show, status: :created, location: @post }
      else
        flash.now[:alert] = "Something went wrong! Please try again"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Update successful!!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Update unsuccessful :( please try again"
      render :edit
    end 
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  # def get_user
  #   post = Post.find_by(id: params[:id])
  #   @user = User.find_by(id: post.user_id)
  # end

  def post_params
    params.require(:post).permit(:image, :caption, :username)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(username: params[:username])

    if !!@user && @user.authenticate(params[:password])
      flash.now[:success] = "Welcome back, #{@user.username}!!"
      session[:username] = @user.username
      redirect_to posts_path
    else
      p 'login failed'
      flash.now[:alert] = "Something went wrong! Please check your password and email are correct"
      redirect_to login_path
    end
  end

  def destroy
    redirect_to posts_path, notice: "Bye, #{session[:username]}!!"
    session[:username] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = "Thanks for signing up! Welcome to InstaBAM!!"
        format.html { redirect_to posts_url }
        format.json { render :show, status: :created, location: @user }
        session[:username] = @user.username
      else
        flash.now[:alert] = "Something went wrong! Please try again"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
  end

  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=Yuji+Syuku&display=swap" rel="stylesheet">
    <title>InstaBAM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <nav class="navbar-container">
      <%= link_to posts_path do %>
        <div class='nav-header'>
        InstaBAM!!!
        </div>
      <% end %>
      <div class='link'>
        <% if session[:username] %>
          Hi, <%= session[:username] %>!! ~  
          <%= link_to new_post_path do %>
            New post! 
          <% end %>
           ~ 
          <%= link_to logout_path do %>
              Log out!
          <% end %>
        <% else %>
          <%= link_to new_user_path do %>
              Sign up!
          <% end %>
          <%= link_to login_path do %>
              Log in!
          <% end %>
        <% end %>
      </div>
    </nav>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class='flash'>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class='form-wrapper'>
  <%= form_for @post do |form| %>
    <%= form.label :caption %><br>
    <%= form.text_field :caption %><br>
    <%= form.label :image %>
    <%= form.file_field :image %><br>
    <%= form.submit "Submit" %>
    <%= form.hidden_field :username, :value => session[:username] %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class='post-wrapper'>
  <div class='post'>
    <% if post.username == session[:username] %>
      <div class='username'>
        You posted this!!
      </div>
      <div class='link'>
        <%= link_to edit_post_path(post) do %>
          Edit!!
        <% end %>
      </div>
      <% else %>
      <div class='username'>
        <%= post.username %> posted this!
      </div>
      <% end %>
    <div class='image'>
      <%= image_tag post.image.variant(resize_to_limit: [700, nil]) %>
    </div>
    <div class='caption'>
      <%= post.caption %><br>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class='header'>
  Edit your post!!
</div>
<div class='posts-wrapper'>
  <div class='post'>
    <div class='image'>
      <%= image_tag @post.image.variant(resize_to_limit: [700, nil]) %>
    </div>
    <div class='caption'>
      <%= @post.caption %>
    </div>
  </div>
</div>
<%# <div class='link'>
  <%= link_to destroy_post_path(@post), method: :delete, data: {confirm: "You sure??!" } do %>
  <%# Delete your lovely post!!
  <% end %>
<%# </div> %>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= link_to post_path(post) do %>
    <%= render "post", post: post %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<div class='header'>
  Post a picture!!
</div>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= render "post", post: @post %>

app/views/users/_form.html.erb
<div class='form-wrapper'>
  <%= form_with(model: user) do |form| %>
    <% if user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :username, style: "display: block" %>
      <%= form.text_field :username %>
    </div>

    <div>
      <%= form.label :email, style: "display: block" %>
      <%= form.text_field :email %>
    </div>

    <div>
      <%= form.label :password, style: "display: block" %>
      <%= form.text_field :password %>
    </div>

    <div>
      <%= form.submit "Do it!!" %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<div class='header'>
  Sign up!!!
</div>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>